.gitignore, Makefile, README.md, cmd/accelctl/main.go, cmd/acceld/main.go, go.mod, pkg/client/client.go, pkg/client/convert.go, pkg/converter/converter.go, pkg/router/router.go, pkg/router/task_create.go, pkg/router/task_list.go, pkg/task/manager.go, test/integration_test.go
Add a CLI tool named `accelctl` for creating tasks and listing their status.
Usage:
```
$ accelctl task create <source-image-reference>
$ accelctl task list
```
Close https://github.com/goharbor/acceleration-service/issues/6
=> Add CLI tool to manage conversion tasks

README.md, misc/config/config.yaml.nydus.tmpl
There are some typo/invalid command in reademe, this commit
will fix these.
And also changed the suffix for nydus from converted to nydus.
Signed-off-by: bin liu <liubin0329@gmail.com>
=> Fix some readme mistakes

pkg/driver/nydus/packer/layer.go, pkg/driver/nydus/packer/mount.go
If some error occurs in `mountWithLower`, will cause that panic
on umount in defer function:
```
panic: close of nil channel
pkg/driver/nydus/packer.(*BuildLayer).umount(...)
pkg/driver/nydus/packer/layer.go:93
```
Fix it by checking nil channel, the root cause is an error be
returned from GetOverlayLayers:
```
error: unknown option redirect_dir specified by snapshotter.
```
Fix it by updating ported code.
=> Nydus: fix panic on layer umount

misc/config/config.yaml.nydus.tmpl, pkg/driver/nydus/builder/builder.go, pkg/driver/nydus/nydus.go, pkg/driver/nydus/packer/layer.go, pkg/driver/nydus/packer/packer.go, pkg/driver/nydus/utils/constant.go
- Support to build nydus RAFS v6 version format (EROFS-compatible).
- Record nydus RAFS version to the annotation of bootstrap layer.
=> Nydus: support rafs v6 version

misc/config/config.yaml.nydus.tmpl, pkg/driver/nydus/backend/backend.go, pkg/driver/nydus/backend/localfs.go
Support for writing nydus blob to a specified directory, it's used in the case where the user wants to handle nydus blob themselves (upload blobs to the specified remote storage and do blob garbage collection by themselves).
=> Nydus: support localfs backend

.github/workflows/integration-test.yml, README.md, cmd/accelctl/main.go, script/integration/one-time.sh
Some users want to do a one-time image conversion without starting
acceld service, so we can provide a one-time mode that allows
accelctl to convert images locally:
```
accelctl convert --config /path/to/config.yaml localhost/library/nginx:latest
```
Close #21 
=> Accelctl: support one-time mode

misc/config/config.yaml.nydus.tmpl, pkg/content/content.go, pkg/driver/nydus/nydus.go, pkg/driver/nydus/utils/utils.go
Support `merge_manifest: true` option to enable nydus driver
to merge OCIv1 manifest and nydus manifest into a manifest
index in the target image, it's used for containerd to support
running OCIv1 image or nydus image simultaneously with a
single image reference.
Close https://github.com/goharbor/acceleration-service/issues/18
=> Nydus: support merging manifest

misc/config/config.yaml.estargz.tmpl, misc/config/config.yaml.nydus.tmpl, pkg/config/config.go, pkg/converter/annotation/annotation.go, pkg/converter/converter.go, pkg/driver/driver.go, pkg/driver/estargz/estargz.go, pkg/driver/nydus/nydus.go, pkg/driver/nydus/packer/packer.go
Add option `harbor_annotation: true` to append harbor specified annotations
to the manifest of converted image:
```
{
...
annotation：{
"io.goharbor.artifact.v1alpha1.acceleration.type": "estargz"
"io.goharbor.artifact.v1alpha1.acceleration.source.digest": "sha256:dbad66bcfe29ef383157a3e122acbd08cd2ebd40f5658afa2ae62c52ffe26e9f"
}
}
```
The first annotation is used to identify different accelerated image
formats in harbor.
The second annotation is used to reference the source (original) image,
which can be used to avoid duplicate conversion or track the relationship
between the source image and converted image in harbor portal.
Close https://github.com/goharbor/acceleration-service/issues/3
=> Converter: adding annotations to track converted image

pkg/driver/nydus/backend/backend.go, pkg/driver/nydus/backend/localfs.go, pkg/driver/nydus/backend/oss.go, pkg/driver/nydus/packer/layer.go
When enabling localfs backend, and have multiple same blobs output in diff build,
maybe acceld throws the following error:
```
export nydus blob: open blob ...: no such file or directory
```
The root cause is the blob be moved to localfs target directory in goroutine A,
then the goroutine B will fail in opening the blob file before moving.
Fix it by checking blob existence in backend before pushing to backend,
and the concurrent pushes are protected by singleflight.
=> Nydus: fix move blob in localfs backend

.github/workflows/integration-test.yml, misc/config/config.yaml.nydus.tmpl, pkg/content/content.go, pkg/converter/annotation/annotation.go, pkg/converter/converter.go, pkg/driver/nydus/builder/builder.go, pkg/driver/nydus/export/export.go, pkg/driver/nydus/layer.go, pkg/driver/nydus/nydus.go, pkg/driver/nydus/packer/layer.go, pkg/driver/nydus/packer/packer.go, pkg/driver/nydus/parser/parser.go, pkg/driver/nydus/utils/utils.go, pkg/utils/utils.go
```
Nydus uses a special chunk-dict image for chunk-leveled data
deduplication, the PR support importing the image during
image conversion.
It pulls nydus chunk-dict image from remote registry, writes all
layers into containerd content store, then provide chunk-dict
bootstrap to nydus-image.
Use `chunk_dict_ref` option in nydus driver configuration to
enable this feature.
```
=> Nydus: support importing chunk dict

pkg/driver/nydus/export/export.go, pkg/driver/nydus/packer/packer.go, pkg/driver/nydus/utils/constant.go
We should append the blob list into the annotation of bootstrap
layer, this blob list is used to GC in nydus snapshotter.
In the future, this annotation should be deprecated, but now we
should keep compatibility for the current version of nydus snapshotter:
https://github.com/containerd/nydus-snapshotter/issues/5
=> Nydus: fix lost blob list in bootstrap layer

README.md, pkg/converter/converter.go, pkg/errdefs/errors.go, pkg/handler/handler.go, pkg/router/health.go, pkg/router/router.go
Provide a health check API `GET /api/v1/health` to harbor,
it checks the acceld service is healthy and can serve webhook
request from harbor.
=> API: add health check endpoint

pkg/driver/nydus/export/export.go
When exporting the image, the chunk dict blob's diff id isn't correctly
handled, so the nydus snapshotter goes wrong when preparing layer,
leads to containerd raises error `failed to extract layer : failed to get
stream processor for application/vnd.oci.image.layer.nydus.blob.v1: no
processor for media-type: unknown`.
To fix this bug, due to the nydus blob digest is the same as diff id,
we use blobDesc.Digest as layer diff id directly.
Signed-off-by: Qi Wang <wangqi@linux.alibaba.com>
=> nydus: fix empty diff id for the blob layer of chunk dict

pkg/content/content.go, pkg/converter/converter.go, pkg/driver/nydus/nydus.go, pkg/driver/nydus/utils/utils.go, pkg/utils/utils.go
Write a diff id label of layer in content store for simplifying
diff id calculation to speed up the conversion.
See: https://github.com/containerd/containerd/blob/e4fefea5544d259177abb85b64e428702ac49c97/images/diffid.go#L49
=> converter: simplify diff id calculation

pkg/driver/nydus/merge.go, pkg/driver/nydus/nydus.go
The merge operation should be passed with chunk dict bootstrap
path, otherwise will panic with this error:
Error: invalid bootstrap, seems have multiple non-chunk-dict
blobs in this bootstrap
=> nydus: fix panic on using chunk dict

Makefile, cmd/accelctl/main.go, cmd/acceld/main.go
So that we can inspect the binary tag version using:
```
$ acceld --version
acceld version v0.1.0
```
=> makefile: build version tag into binary

misc/config/config.yaml.estargz.tmpl, misc/config/config.yaml.nydus.tmpl, pkg/content/content.go, pkg/converter/converter.go, pkg/driver/nydus/nydus.go, pkg/driver/nydus/parser/parser.go, pkg/errdefs/errors.go, pkg/remote/resolve.go
```
An error is thrown when converting image to HTTPS registry with
self-signed TLS cert:
failed to do request: x509: certificate signed by unknown authority
We currently do not provide any option for the HTTPS registry to skip
insecure self-signed certificate verification, so this commit changes
the semantics of the previous `insecure: true` option to support it.
if users specify this option, then skips verifying HTTPS certs.
And this commit allows acceld automatically fallback to plain HTTP
if the first HTTPS request fails for an HTTP registry when whether
or not the `insecure: true` option is enabled.
```
=> converter: support skipping tls verification

go.mod, go.sum, misc/config/config.estargz.yaml, misc/config/config.nydus.ref.yaml, misc/config/config.nydus.yaml, pkg/adapter/adapter.go, pkg/config/config.go, pkg/content/content.go, pkg/content/local.go, pkg/converter/converter.go, pkg/converter/opts.go, pkg/driver/driver.go, pkg/driver/estargz/estargz.go, pkg/driver/nydus/nydus.go, pkg/platformutil/platformutil.go, pkg/utils/utils.go
**nydus: support more options**
- Add `backend_force_push` option;
- Add `docker2oci` option;
- Add `fs_align_chunk` option;
- Add `fs_chunk_size` option;
- Add `prefetch_patterns` option;
See `misc/config/config.nydus.yaml` for option explanation.
**refine converter codes**
- Rename `LocalConverter` to `Converter`;
- Should enable `UpdateLayerDiffID` func ability in exported `Converter`;
- Move `LocalProvider` codes into separate file;
**support converting images for specific platforms**
Allow users specify `platforms` option in configuration to convert
images for specific platforms, leave empty for all platforms.
=> nydus: support more options

go.mod, go.sum, pkg/driver/nydus/nydus.go
Add the batch-size arg for nydusify and the batch-size arg is new feature for nydus-image, which support merge small file chunks into one batch chunk.
That is the third part of work , the first part work is in [nydus-snapshotter](https://github.com/containerd/nydus-snapshotter/pull/445), and the second is https://github.com/dragonflyoss/image-service/pull/1206
This PR is related to https://github.com/dragonflyoss/image-service/pull/1202.
=> feat: support the arg batch-size for small chunks mergence in nydus-image

pkg/converter/converter.go, pkg/converter/metric.go, pkg/driver/nydus/nydus.go
When we pull the image, we filter the platform, but the index descriptor will include all platforms. In that case, when we need to calculate the SourceImageSize, we will get error platform manifests. We can't find blobs locally.
=> fix: filter platforms when set metric ImageSize

README.md, go.mod, misc/config/config.estargz.yaml, misc/config/config.nydus.ref.yaml, misc/config/config.nydus.yaml, pkg/adapter/adapter.go, pkg/config/config.go, pkg/content/local.go, pkg/content/ported.go
Acceld depend on local containerd service, we should replace it by create content store by containerd pkg.
We use [github.com/containerd/containerd/content/local](https://github.com/containerd/containerd/tree/main/content/local) to remove containerd service dependency.
Break Change:
1. remove containerd config.
2. add work_dir in provider for content store work.
resolve #137.
=> feat: remove containerd service dependency

.github/workflows/integration-test.yml, pkg/adapter/adapter.go, pkg/content/ported.go
When ```acceld``` handles highly concurrent conversion tasks, the content store will be locked because of fetching the same layer. 
1. Add singleflight in ```LocalAdapter.Dispatch```. If the image ref is the same, we only convert once simultaneously.
2. Add singleflight in ```fetchHandler```. If the ```desc.Digest``` is the same, we only fetch once simultaneously.
In Integration Test, we can move accel check out of build, it will make ci faster.
resolve #46.
=> feat: resolve error in highly concurrent by singleflight

pkg/content/content.go, pkg/content/content_test.go, pkg/content/local.go, pkg/content/ported.go, pkg/content/store.go
To complete more custom features of the content store. We need to wrap the ```content.store``` to call the function inner store.
Changes:
- Add new type Store to wrap ```content.store```.
- Move ```UpdateTime``` call from ```fetch``` to ```Store.ReaderAt```.
- Move ```newStore``` and ```NewDB``` to ```newContent```.
Reference: https://github.com/goharbor/acceleration-service/issues/141.
=> feat: add new type Store in content

misc/config/config.nydus.ref.yaml, misc/config/config.nydus.yaml, pkg/driver/nydus/nydus.go
With `with_referrer: true`, we can track all nydus images associated with
an OCI image. For example, in Harbor we can cascade to show nydus
images linked to an OCI image, deleting the OCI image can also delete
the corresponding nydus images. At runtime, nydus snapshotter can also
automatically upgrade an OCI image run to nydus image.
=> nydus: support with_referrer option

pkg/content/bucket.go, pkg/content/content.go
Now acceld's ```GarbageCollect``` will clear all caches when content size is over the threshold. We should use the lease to choose which content blob should be reserved. The ```updatedAt``` can help us to choose blobs.
Changes:
- Rename the ```updatedAt``` to ```usedat``` and move to lease bucket (labels).
- Add the ```usedCountLabel``` in lease bucket.
- Rewrite GC by lease. When the local cache size is over eighty percent of the threshold, gc will delete local blobs until the size is less than eighty percent of the threshold which is order by ```usedat```(LRU).
TODO:
We should update the order of GC from ```LRU``` to ```LRFU``` by ```usedCountLabel```.
Reference: https://github.com/goharbor/acceleration-service/issues/141.
=> feat: use lease to manage local cache for gc

pkg/adapter/adapter.go, pkg/content/content.go
To resolve the concurrent race issue, now gc will wait for all converting tasks completed.
resolve https://github.com/goharbor/acceleration-service/issues/174.
=> fix: gc works unexpeted in high concurrent

.github/workflows/concurrent-test.yml, script/integration/concurrent/config.yaml, script/integration/concurrent/test-diff.sh, script/integration/concurrent/test-same.sh
- Test the same image conversion tasks in high concurrent.
- Test the different image conversion tasks in high concurrent.
Ref: #174
=> gha: add concurrent test

misc/config/config.nydus.ref.yaml, misc/config/config.nydus.yaml, pkg/adapter/adapter.go, pkg/adapter/rule.go, pkg/config/config.go, pkg/errdefs/errors.go
Now  same repoes with different tag converts with same cache repo, but the cache tag is different. This will result in very few or even no use of the cache layer in the converted cache, so we have make the same repo using the same tagged cache repo.
change
- make cache repo with same tag
=> fix: use same cache repo for different tagged repo

pkg/adapter/adapter.go, pkg/content/content.go
- Add scheduled GC task, we will start GC every hour. 
- It will start the schedule after creating LocalAdapter. 
- The scheduled GC task will reduce local storage to less than 40 percent of the threshold.
Ref: #141
=> gc: add scheduled gc task

.github/workflows/concurrent-test.yml, .github/workflows/integration-test.yml, .github/workflows/release.yml, .github/workflows/unit-test.yml
Changes:
- update [actions/checkout](https://github.com/actions/checkout) to v4.
- add linux/arm64 release binary for `acceld` and `accelctl`.
=> release: add linux-arm64 binary

pkg/adapter/adapter.go, pkg/content/content.go
```GC``` errors do not affect subsequent conversion tasks, so separate ```gc``` and ```convert``` by ```goroutine``` go and don't return ```error``` in ```GC```.
Changes:
- GC doesn't return any error, change to the error log.
- Change gc call to ```goroutine```.
Ref: #141
=> chore: separate gc and convert

.github/workflows/release.yml
Fix an error created in https://github.com/goharbor/acceleration-service/pull/186.
We should checkout the repo in upload_binary.
=> fix: checkout code in release upload_binary

pkg/adapter/adapter.go, pkg/errdefs/errors.go
If acceld converts with different fs version cache, leading to an inconsistent fs version problem when merging into boostrap layer. 
For example: cache manifest fs version is 5 and convert fs version is 6, this will lead to compatibility problems.
So a simple way is that  retrying without remote cache.
changes:
- Retry in adapter convert when encounter compatibility problems.
- move clear cache in provider
=> fix: retry without cache in inconsistent fs version

docs/development.md, pkg/adapter/adapter.go, pkg/metrics/metrics.go, pkg/task/manager.go
We have collected the metrics of conversion progress. Let's show them in the task. Add the `SourceImageSize` and `TargetImageSize` in the task and record them when the task is finished.
resolve #191.
=> feat: record metrics of conversion in task

.github/workflows/integration-test.yml
We have test `wordpress` `nginx` `alpine` and `busybox` in Concurrent Test. 
Change test image in Integration Test from `wordpress` to `redis` to reduce test time and test more different images.
=> action: change wordpress to redis

pkg/adapter/adapter.go
```
adp.content.GcMutex.RLock()
defer adp.content.GcMutex.RUnlock()
```
We use `RUnlock()` twice.
Signed-off-by: Yadong Ding <ding_yadong@foxmail.com>
=> fix: delete repetitive unlock

pkg/adapter/adapter.go, pkg/task/manager.go
Create a new `boltdb` for manager to persistent task worker queues in database.
Changes:
- Init manager when creat `LocalProvider`.
- Load task queues from `boltdb` when init manager.
- Manager syncs task queues with `boltdb` when `Create` or `Finish` task. 
resolve #5.
=> feat: persistent task worker queues

misc/config/config.estargz.yaml, misc/config/config.nydus.ref.yaml, misc/config/config.nydus.yaml, pkg/config/config.go, pkg/handler/handler.go, script/integration/concurrent/config.yaml
User can don't put the auth in config file, just use `docker/nerdctl login`. 
Acceld will try to read registry auth from the docker config if cant't find auth in config file.
resolve #29 .
=> feat: support reading auth from docker config

pkg/adapter/adapter.go
Error should be return when encountered in cache reference mapping.
=> fix: return cache map error when encountered

pkg/adapter/adapter.go, pkg/content/cache.go, pkg/content/cache_test.go, pkg/content/content.go, pkg/content/content_test.go, pkg/content/local.go, pkg/content/provider.go, pkg/converter/converter.go, pkg/driver/nydus/nydus.go, pkg/errdefs/errors.go
We can use `manifestIndex `to record different remote cache on different plantforms.
And conversion will use cache which matches current plantfotm.
changes:
- use manifest list to store different cache on different plantforms.
=> feat: handle different plantform in cache remote

pkg/cache/cache.go, pkg/content/content.go, pkg/converter/converter.go
If use `info` varible in `Update` of store and get error in store update, the return value `info` is empty, and cache `Update` will be useless.
change:
- rename `info` to `updateInfo`  in content wrap
- `Update` func of cache needs a mutex protection
- add cached info of a conversion like  log info 
"pulled image xxx(cached 21/23)"
"......"
"converted image xxx(cached 21/23)"
"......"
=> fix: blob lost and lack mutex protection

.github/workflows/dco-check.yml, .github/workflows/release.yml, README.md, script/release/Dockerfile
Since we have arm64 release binaries, we can also build arm64 images.
Ref: https://docs.docker.com/build/ci/github-actions/multi-platform.
1. set up `latest` version.
2. change the image tag from `v0.x.x` to `0.x.x`.
3. upload repo description.
4. support the `linux/arm64` image.
Test in my repo:
release action: https://github.com/Desiki-high/acceleration-service/actions/runs/7443126413
docker hub image: https://hub.docker.com/r/dingyadong/harbor-acceld and tag [0.2.8](https://hub.docker.com/layers/dingyadong/harbor-acceld/0.2.8/images/sha256-8f2030d5d04e72ffa328bcb8ef17625c5c33e602e780ee52f2dfcd5d2685a1e9?context=explore).
=> feat: build arm64 image

.github/workflows/unit-test.yml, pkg/adapter/rule.go, pkg/adapter/rule_test.go
ref: #249.
Convert source image such as `repo:tag@sha256xxxxxx` or `repo@sha256xxxxxx`.
=> feat: support sha256 format image

pkg/errdefs/errors.go
For some registry servers whose gateway has https on port 443 but
does not forward the request to the registry server, an io timeout
error occurs and we may need to fallback to http as well.
=> errdefs: add timeout case for NeedsRetryWithHTTP

pkg/driver/nydus/nydus.go, pkg/driver/nydus/utils/constant.go
The os.features field that gets added when creating index manifests in a merged-platform situation is causing issues with some registries like ECR as they don't accept this field despite being part of the OCI spec. Since the field is currently only supported by build tools and not by any runtime, we think it's fine to remove it and replace it by the `artifactType` field which is accepted by ECR.
That's technically a breaking change as tooling that was relying on this field would stop working so that might be worth a specific release note
cc @imeoer
=> [nydus] Use artifactType instead of os.features

pkg/driver/nydus/nydus.go, pkg/driver/nydus/nydus_test.go
Add an empty tar.gz layer at the beginning of the OCI image that's referrenced in the nydus merged-manifest compared to the original OCI one. This empty layer, being the first layer, will force the OCI image to have a completely different chainID from its original counterpart. This is done so that containerd and other runtimes don't try to reuse the OCI layers for other images that share layers with the original OCI variant. The drawback being that nydus-merged images can't share layers with pure OCI images when they are pulled on non-nydus clients.
The choice to use an empty tar.gz layer as the new first layer is because:
- this is a format understood by every runtime (on the other hand, docker doesn't understand layers that use `application/vnd.oci.empty.v1+json`)
- an empty layer won't …
=> [nydus] Add empty layer in OCI image when merging platforms
