pkg/driver/nydus/packer/layer.go
pkg/driver/nydus/packer/packer.go

In one-time mode, the exit of accelctl will cause the temporary
directory mounted by `containerd#mount.WithTempMount` not to be
umounted in time, causing mountpoints to leak.
Fix: ensure all mounts are umounted using `errorgroup#Wait()`
before process exit.

Nydus: fix mount leak after process exit

---

README.md

Doc: add driver introduction

---

README.md

Doc: add api definition

---

.github/workflows/release.yml
Makefile
script/release/Dockerfile
script/release/entrypoint.sh

Add github action configuration to release acceld, accelctl binaries and image for the committed tag.
A successful release job can be found here: https://github.com/imeoer/acceleration-service/actions/runs/2164975305
Close #11

Action: add release workflow

---

pkg/content/content.go
pkg/driver/nydus/nydus.go
pkg/server/server.go

Signed-off-by: Changwei Ge <chge@linux.alibaba.com>

correct a few spelling and grammar mistakes

---

misc/config/config.yaml.nydus.tmpl
pkg/driver/nydus/builder/builder.go
pkg/driver/nydus/nydus.go
pkg/driver/nydus/packer/packer.go

Apart from LZ4, let's add Zstd support too.
Signed-off-by: Gao Xiang \<hsiangkao@linux.alibaba.com\>

nydus: support more compression algorithms

---

pkg/driver/nydus/convert.go

For nydus layer, we can write a diff id label of layer in
content store for simplifying diff id calculation to speed
up the conversion.
See: https://github.com/containerd/containerd/blob/e4fefea5544d259177abb85b64e428702ac49c97/images/diffid.go#L49
This improvement is related with https://github.com/goharbor/acceleration-service/pull/48.
Performance test (with `localfs` backend, cleanup containerd cache before each test case):
| image           | acceld version | fs version | time   |
| --------------- | -------------- | ---------- | ------ |
| wordpress:5.9.2 | new (this pr)  | v5         | 13.47s |
| wordpress:5.9.2 | new (this pr)  | v6         | 13.41s |
| wordpress:5.9.2 | old (3f8e946)  | v5         | 17.47s |
| wordpress:5.9.2 | old (3f8e946)  | v6         | 18.17s |
Signed-off-by: …

nydus: simplify diff id calculation

---

go.mod
go.sum
misc/config/config.nydus.ref.yaml
pkg/driver/nydus/nydus.go

Support nydus zran image conversion, related introduction:
https://github.com/dragonflyoss/image-service/blob/master/docs/nydus-zran.md

nydus: support zran ref image conversion

---

pkg/adapter/adapter.go
pkg/converter/converter.go
pkg/converter/metric.go

**We need to collect the converter metric for nydusify, such as conversion time image size.**
Related: https://github.com/dragonflyoss/image-service/issues/1263

feat: add metric for converter

---

go.mod
go.sum
pkg/driver/nydus/nydus.go

Support convering oci image to encrypted nydus image.
Related Issue [here](https://github.com/dragonflyoss/image-service/issues/1334)

feat: support convertion to encrypted nydus image

---

pkg/content/content.go

Labels in db will cause the blobs of the same image to be related to each other and can only be cleaned at the same time.
- not write in ```content.Store.Update```.
- not write in ```content.Writer.Commit```.
We add LocalWriter to wrap writer in the content store to make sure not to write any labels in boltdb. In that case, we can make gc work well with the lease.
Changes：
- add ```LocalWriter```.
- rewrite ```content.Writer.Commit``` method.
Ref: #141

feat: add localWriter

---

.github/workflows/concurrent-test.yml
.github/workflows/integration-test.yml
.github/workflows/unit-test.yml

Add paths-ignore in GitHub action.

gha: add paths-ignore

---

.github/workflows/concurrent-test.yml
.github/workflows/integration-test.yml
script/integration/harbor.yml

deps: bump harbor from 2.4.1 to 2.8.4

---

script/release/Dockerfile
script/release/entrypoint.sh

Remove containerd in release Dockerfile
Update nydus from v2.1.5 to v2.1.6

release: remove containerd

---

README.md
docs/garbage-collection.md

Signed-off-by: Yadong Ding <ding_yadong@foxmail.com>

docs: add garbage-collection.md for gc

---

.github/workflows/webhook-test.yml
script/integration/webhook/config.yaml
script/integration/webhook/test.sh

We should test if webhook work happy.

action: add webhook test

---

go.mod
go.sum
pkg/cache/cache.go
pkg/content/cache.go
pkg/content/cache_test.go
pkg/content/content.go
pkg/content/content_test.go
pkg/content/lease.go
pkg/content/local.go
pkg/content/provider.go
pkg/converter/converter.go
pkg/driver/nydus/nydus.go
pkg/driver/nydus/utils/constant.go
pkg/remote/ported.go

1. Remote cache should also work for pulling source layer
2. Fix possible conversion hang when only hit part of cache items.
3. Some other improvements for code design

cache: a series of fixups for remote cache

---

.github/workflows/release.yml

Fix https://github.com/goharbor/acceleration-service/actions/runs/6529707059/job/17727847276

action: fix unauthorized issue on release

---

misc/config/config.nydus.ref.yaml
misc/config/config.nydus.yaml
pkg/cache/cache.go
pkg/config/config.go
pkg/content/local.go
pkg/converter/converter.go

add cache version information
changed:
- add cache version and check if version matched

feat: add cache version

---

.gitignore
Makefile
misc/acceleration-daemon.service

1. add systemd service `acceleration-daemon.service`.
2. add make install for installing `acceleration-daemon.service`.
resolve #223.

feat: add systemd service

---

.github/workflows/concurrent-test.yml
.github/workflows/integration-test.yml
.github/workflows/webhook-test.yml
script/integration/harbor.yml

Get latest version by `Github API`.

action: keep latest nydus and harbor version

---

go.mod
go.sum
pkg/driver/nydus/nydus.go

Use MergeOption.MergeManifest introduced in nydus-snapshotter v0.15.3 (https://github.com/containerd/nydus-snapshotter/pull/674)

[nydus] Propagate mergeManifest to snapshotter converter
